name: capstone
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin: ^0.7.3  # Replace with the latest version
  vector_math: ^2.1.0
  provider: ^6.0.5
  fl_chart: ^0.68.0
  intl: any
  shared_preferences: any
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.0.9  # M
  visibility_detector: ^0.4.0+2
  photo_view: ^0.15.0
  permission_handler: ^10.2.0
  video_player: ^2.5.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/videos/logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/videos/logo.png
    - assets/videos/microscopy/microscope1.mp4
    - assets/videos/microscopy/microscope2.mp4
    - assets/videos/levels/biological.mp4
    - assets/videos/cell/cell1.mp4
    - assets/videos/cell/cell2.mp4
    - assets/videos/bacteria/bacteria1.mp4
    - assets/videos/bacteria/bacteria2.mp4
    - assets/videos/bacteria/bacteria3.mp4
    - assets/videos/heredidty/heredity1.mp4
    - assets/videos/heredidty/heredity2.mp4
    - assets/videos/heredidty/heredity3.mp4
    - assets/videos/heredidty/heredity4.mp4
    - assets/videos/heredidty/heredity5.mp4
    - assets/videos/ecosystem/eco1.mp4
    - assets/videos/ecosystem/eco2.mp4
    - assets/videos/ecosystem/eco3.mp4
    - assets/videos/ecosystem/eco4.mp4
    - assets/videos/ecosystem/eco5.mp4
    - assets/videos/ecosystem/eco6.mp4
    - assets/videos/ecosystem/eco7.mp4
    - assets/videos/ecosystem/eco8.mp4
    - assets/images/homepage/6ecosystem.png
    - assets/images/homepage/5dna.png
    - assets/images/homepage/4bacteria.png
    - assets/images/homepage/3cells.png
    - assets/images/homepage/2biological.png
    - assets/images/homepage/1microscopy.png
    - assets/images/homepage/progress.png
    - assets/images/homepage/tutorial.png
    - assets/VideoTutorial/video.mp4
    - assets/images/quiz/bacteria.png
    - assets/images/quiz/cell.png
    - assets/images/quiz/ecosystem.png
    - assets/images/quiz/hereditary.png
    - assets/images/quiz/levels.png
    - assets/images/quiz/microscopy.png
    - assets/images/homepage/1.png
    - assets/images/homepage/2.png
    - assets/images/quiz/quiz_icons/bacteria.png
    - assets/images/quiz/quiz_icons/eco.png
    - assets/images/quiz/quiz_icons/heredity .png
    - assets/images/quiz/quiz_icons/microscope.png
    - assets/images/quiz/quiz_icons/organization.png
    - assets/images/quiz/quiz_icons/plant-cell.png
    - assets/images/Microscopy/worksheet1.jpg
    - assets/images/Microscopy/worksheet2.jpg
    - assets/images/
    - assets/images/Microscopy/Zacharias.jpg
    - assets/images/Microscopy/compound_.jpg
    - assets/images/Microscopy/Collage.png
    - assets/images/Microscopy/label.png
    - assets/images/Microscopy/Answer.png
    - assets/images/organization/atom.png
    - assets/images/organization/molecule.png
    - assets/images/organization/cell.png
    - assets/images/organization/cardiac muscle.jpg
    - assets/images/organization/heart.jpg
    - assets/images/organization/system.jpg
    - assets/images/organization/bison.jpg
    - assets/images/organization/group.jpg
    - assets/images/organization/community.jpg
    - assets/images/organization/ecosystem.jpg
    - assets/images/organization/savana.jpg
    - assets/images/organization/biosphere.jpg
    - assets/images/cells/bacteria cell.png
    - assets/images/cells/plant cell.png
    - assets/images/cells/cell comparison .jpeg
    - assets/images/cells/bacteria cell.png
    - assets/images/cells/plant cell.png
    - assets/images/cells/red blood cells.jpg
    - assets/images/cells/squamous cell.jpg
    - assets/images/cells/neuron.jpg
    - assets/images/cells/bone cell.jpg
    - assets/images/cells/columnar cell.jpg
    - assets/images/cells/smooth muscle cell.jpg
    - assets/images/cells/cell comparison .jpeg
    - assets/images/bacteria/bactirum.jpg
    - assets/images/bacteria/gram positive and negative .jpg
    - assets/images/bacteria/cocci.png
    - assets/images/bacteria/bacilli.jpg
    - assets/images/bacteria/spirilla.jpg
    - assets/images/bacteria/entamoeba histolytica.jpg
    - assets/images/bacteria/#1 trypanosoma.png
    - assets/images/bacteria/#2 trypanosoma.png
    - assets/images/bacteria/t.jpeg
    - assets/images/bacteria/trichonympha.jpg
    - assets/images/bacteria/plasmodium.jpg
    - assets/images/bacteria/Anopheles mosquito.jpg
    - assets/images/bacteria/plantlike.jpg
    - assets/images/bacteria/Penicillium notatum.jpg
    - assets/images/bacteria/2.jpg
    - assets/images/bacteria/Saccharomyces cerevisiae.png
    - assets/images/bacteria/ring.jpg
    - assets/images/bacteria/fungi.jpg
    - assets/images/bacteria/mycorrhizal fungi.jpg
    - assets/images/heredity/trivia.jpg
    - assets/images/heredity/spawning.jpeg
    - assets/images/heredity/mating.jpg
    - assets/images/heredity/Fertilization.jpg
    - assets/images/heredity/Schema conjugation.png
    - assets/images/heredity/budding.jpg
    - assets/images/heredity/budding2.jpg
    - assets/images/heredity/binary.jpg
    - assets/images/heredity/long.jpg
    - assets/images/heredity/am.jpg
    - assets/images/heredity/starfish.png
    - assets/images/heredity/planarian.jpg
    - assets/images/heredity/lizard.jpg
    - assets/images/heredity/prothallus.jpg
    - assets/images/heredity/sporophyte.jpg
    - assets/images/heredity/sporo and game.jpg
    - assets/images/heredity/2#fungus.jpg
    - assets/images/heredity/run.jpg
    - assets/images/heredity/suckers.jpg
    - assets/images/heredity/tubers.jpg
    - assets/images/heredity/taro.jpg
    - assets/images/heredity/re.jpg
    - assets/images/heredity/o.jpg
    - assets/images/heredity/grafting.jpg
    - assets/images/heredity/tissue culture.jpg
    - assets/images/ecosystem/macroecosysytem.jpg
    - assets/images/ecosystem/colony.jpg
    - assets/images/ecosystem/fox.jpg
    - assets/images/ecosystem/trivia2.jpg
    - assets/images/ecosystem/red.jpg
    - assets/images/ecosystem/rock.jpg
    - assets/images/ecosystem/lotus.jpg
    - assets/images/ecosystem/santan.jpg
    - assets/images/ecosystem/cactus.jpg
    - assets/images/ecosystem/sand.jpg
    - assets/images/ecosystem/organization.jpg
    - assets/images/ecosystem/energy flow.jpg
    - assets/images/ecosystem/food chain.jpg
    - assets/images/ecosystem/food web2.jpg
    - assets/images/ecosystem/trico.jpg
    - assets/images/ecosystem/algae.png
    - assets/images/ecosystem/bee.jpg
    - assets/images/ecosystem/shark.png
    - assets/images/ecosystem/tick.jpg
    - assets/images/ecosystem/wallnut.jpeg
    - assets/images/ecosystem/lizard feeding.jpeg
    - assets/images/ecosystem/deer.jpg
    - assets/images/ecosystem/niche.png
    - assets/images/ecosystem/resource.png
    - assets/images/ecosystem/birdy.jpg
    - assets/lesson1&2/
    - assets/lesson1&2/assets/
    - assets/lesson1&2/assets/base/
    - assets/lesson1&2/assets/arm/
    - assets/lesson1&2/assets/microscpe/
    - assets/lesson1&2/assets/condenser/
    - assets/lesson1&2/assets/disk/
    - assets/lesson1&2/assets/focusknob/
    - assets/lesson1&2/assets/knob/
    - assets/lesson1&2/assets/lamp/
    - assets/lesson1&2/assets/lens/
    - assets/hologram/
    - assets/hologram/base/
    - assets/hologram/fine/
    - assets/hologram/coarse/
    - assets/hologram/arm/
    - assets/hologram/eyepiece/
    - assets/hologram/illuminator/
    - assets/hologram/diaphragm/
    - assets/hologram/stage/
    - assets/hologram/objective/
    - assets/hologram/nose/
    - assets/lesson1&2/assets/fine/
    - assets/lesson1&2/assets/coarse/
    - assets/lesson1&2/assets/eye/
    - assets/lesson1&2/assets/diaphragm/
    - assets/lesson1&2/assets/stage/
    - assets/lesson1&2/assets/objective/
    - assets/lesson1&2/assets/nose/
    - assets/lesson1&2/assets/lenses/
    - assets/lesson1&2/assets/lenses/4x/
    - assets/lesson1&2/assets/lenses/8x/
    - assets/lesson1&2/assets/lenses/40x/
    - assets/lesson1&2/assets/lenses/100x/
    - assets/lesson1&2/assets/tray/
    - assets/lesson1&2/assets/slideholder/
    - assets/lesson1&2/assets/specimen/
    - assets/lesson1&2/assets/sim4x/
    - assets/lesson1&2/assets/sim8x/
    - assets/lesson1&2/assets/sim40x/
    - assets/lesson1&2/assets/sim100x/
    - assets/lesson1&2/lesson1Subtitles/AT/
    - assets/lesson1&2/lesson1Subtitles/TLA/
    - assets/lesson1&2/lesson2Subtitles/AT/
    - assets/lesson1&2/lesson2Subtitles/TLA/
    - assets/lesson3/assets/org/
    - assets/lesson3/assets/blocks/
    - assets/lesson3/lesson3Subtitles/AT/
    - assets/lesson3/lesson3Subtitles/TLA/
    - assets/lesson3/levels.png
    - assets/lesson4/
    - assets/lesson4/assets/
    - assets/lesson4/plant2/
    - assets/lesson4/animal2/
    - assets/lesson4/png/
    - assets/lesson4/png/animal/
    - assets/lesson4/png/plant/
    - assets/lesson4/plant2/plantcell.gltf
    - assets/lesson4/lesson4Subtitles/AT/
    - assets/lesson4/lesson4Subtitles/TLA/
    - assets/lesson5/
    - assets/lesson5/assets/
    - assets/lesson5/organelles/
    - assets/lesson5/assets/blocks/
    - assets/lesson5/cell parts/
    - assets/lesson5/cell parts/model images/
    - assets/lesson5/images/
    - assets/lesson6/assets/
    - assets/lesson6/beneficial/
    - assets/lesson6/harmful/
    - assets/lesson6/yogurt/
    - assets/lesson6/milk2curd/
    - assets/lesson8/uterus/
    - assets/lesson8/ooctye/
    - assets/lesson8/spermwithegg/
    - assets/lesson8/cleavage/
    - assets/lesson8/zygote/
    - assets/lesson8/1/
    - assets/lesson8/2/
    - assets/lesson8/3/
    - assets/lesson8/4/
    - assets/lesson8/5/
    - assets/lesson6/question/
    - assets/lesson6/lesson6Subitles/AT/
    - assets/lesson6/lesson6Subitles/TLA/
    - assets/lesson7/
    - assets/lesson7/baby/
    - assets/lesson7/embryo/
    - assets/lesson7/sperm and egg/
    - assets/lesson7/zygote/
    - assets/lesson7/lol/
    - assets/lesson7/sperm/
    - assets/lesson7/coraline/
    - assets/lesson7/fake1/
    - assets/lesson7/fake2/
    - assets/lesson7/mama/
    - assets/lesson7/beldam/
    - assets/lesson7/papa/
    - assets/lesson7/papa2/
    - assets/lesson7/parent/
    - assets/lesson6/AR6.png
    - assets/lesson7/AR7.png
    - assets/lesson6/bread/
    - assets/lesson6/meat/
    - assets/lesson6/pill/
    - assets/lesson6/raw/
    - assets/lesson6/tb/
    - assets/lesson6/cheese/
    - assets/lesson6/tb/source/
    - assets/lesson6/tb/textures/
    - assets/lesson7/for images/
    - assets/lesson10/predation/
    - assets/lesson10/parasitism/
    - assets/lesson10/mutualism/
    - assets/lesson10/competition/
    - assets/lesson10/commensalism/
    - assets/lesson10/lion/
    - assets/lesson10/dog/
    - assets/lesson10/tick/
    - assets/lesson10/hyena/
    - assets/lesson10/shark/
    - assets/lesson10/fish/
    - assets/lesson7/for images/egg cell.jpg
    - assets/lesson7/for images/Sperm Cell.jpg
    - assets/lesson7/for images/male chiken.jpg
    - assets/lesson7/for images/female chiken.jpg
    - assets/lesson7/for images/male frog.jpg
    - assets/lesson7/for images/female frog.jpg
    - assets/lesson7/for images/bee.jpg
    - assets/lesson7/for images/flowers.jpg
    - assets/lesson7/for images/transformation.png
    - assets/lesson7/for images/bacterial-transduction.png
    - assets/lesson7/for images/Binary Fission.png
    - assets/lesson7/for images/budding .png
    - assets/lesson7/for images/Fragmentation-and-Regeneration1.png
    - assets/lesson7/for images/Spore-Formation.png
    - assets/lesson7/for images/vegetative.png
    - assets/lesson7/asexual/
    - assets/lesson7/bird/
    - assets/lesson7/bird/malebird/
    - assets/lesson7/chicken/
    - assets/lesson7/laging error/
    - assets/lesson8/
    - assets/lesson8/AR8.png
    - assets/lesson9/AR9.png
    - assets/lesson11/AR11.png
    - assets/lesson12/AR12.png
    - assets/lesson9/for image/
    - assets/lesson9/for image/chicken.jpg
    - assets/lesson9/for image/cloud.jpg
    - assets/lesson9/for image/flower pot.jpg
    - assets/lesson9/for image/luna.jpg
    - assets/lesson9/for image/mountain.jpg
    - assets/lesson9/for image/nemo.jpg
    - assets/lesson9/for image/stone.jpg
    - assets/lesson9/for image/sun light.jpg
    - assets/lesson9/for image/trees.jpg
    - assets/lesson9/for image/wind mill.jpg
    - assets/lesson10/AR10.png
    - assets/lesson11/for image/
    - assets/lesson11/for image/bizon.jpg
    - assets/lesson11/for image/daga.jpg
    - assets/lesson11/for image/deer dead.jpeg
    - assets/lesson11/for image/deforestation.jpg
    - assets/lesson11/for image/jollibee.jpeg
    - assets/lesson11/for image/seafood lover.jpg
    - assets/lesson11/for image/vegetarian jerry.jpg
    - assets/lesson11/for image/what does the fox say_.jpg
    - assets/lesson11/for image/wolf vs bison.jpg
    - assets/lesson12/for images/
    - assets/lesson12/for images/deforastation.jpg
    - assets/lesson12/for images/drought.jpg
    - assets/lesson12/for images/flood.jpg
    - assets/lesson12/for images/garbage polluton.jpg
    - assets/lesson12/for images/now sunlight.jpeg
    - assets/lesson12/for images/thermal pollution.jpg
    - assets/lesson12/for images/too much sunlight.jpg
    - assets/lesson8/human/
    - assets/lesson8/plants/
    - assets/lesson9/
    - assets/lesson9/cat/
    - assets/lesson9/cloudy/
    - assets/lesson9/fishy/
    - assets/lesson9/tree/
    - assets/lesson9/mushroom/
    - assets/lesson9/rock/
    - assets/lesson9/water/
    - assets/lesson9/wind/
    - assets/lesson9/sun/
    - assets/lesson9/mountain/
    - assets/lesson9/flower/
    - assets/lesson10/
    - assets/lesson10/images/
    - assets/lesson11/bison/
    - assets/lesson11/deer/
    - assets/lesson11/fox/
    - assets/lesson11/mice/
    - assets/lesson11/wolf/
    - assets/lesson11/grass/
    - assets/lesson11/tree/
    - assets/lesson11/fish/
    - assets/lesson11/bee/
    - assets/lesson12/cut/
    - assets/lesson12/garbage/
    - assets/AT images/
    - assets/AT images/week6/
    - assets/AT images/week 7/
    - assets/AT images/week 9/
    - assets/AT images/week12/
#    - assets/lesson7/assets/
#    - assets/lesson7/lesson7Subitles/AT/
#    - assets/lesson7/lesson7Subitles/TLA/
#    - assets/lesson8/assets/
#    - assets/lesson8/lesson8Subitles/AT/
#    - assets/lesson8/lesson8Subitles/TLA/
#    - assets/lesson9/assets/
#    - assets/lesson9/lesson9Subitles/AT/
#    - assets/lesson9/lesson9Subitles/TLA/
#    - assets/lesson10/assets/
#    - assets/lesson10/lesson10Subtitles/AT/
#    - assets/lesson10/lesson10Subtitles/TLA/
#    - assets/lesson11/assets/
#    - assets/lesson11/lesson11Subtitles/AT/
#    - assets/lesson11/lesson11Subtitles/TLA/
#    - assets/lesson12/assets/
#    - assets/lesson12/lesson12Subtitles/AT/
#    - assets/lesson12/lesson12Subtitles/TLA/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
assets/new/microscope/microscope:
  gltf:
